import {getCliClient} from 'sanity/cli'
import {ntCoreEntities} from './data/nt-core.mjs'
const client=getCliClient({apiVersion:'2025-08-15'})
const ids=ntCoreEntities.map((e)=>`historical-entity-${e.id}`)
const rows=await client.fetch(`*[_id in $ids]{_id,id,label,type,epistemicStatus,"sources":count(sources),"relations":count(relations),"brokenRelations":count(relations[!defined(target->_id)])}`,{ids})
const found=new Set(rows.map((r)=>r._id))
const missing=ids.filter((id)=>!found.has(id))
const broken=rows.filter((r)=>r.brokenRelations>0)
const noSources=rows.filter((r)=>!r.sources)
console.log('\n=== AUDIT HISTORICAL EXPLORER · NT CORE ===')
console.log(`Attese: ${ids.length}`)
console.log(`Trovate: ${rows.length}`)
console.log(`Mancanti: ${missing.length}`)
console.log(`Entità con relazioni rotte: ${broken.length}`)
console.log(`Entità senza provenance: ${noSources.length}`)
if(missing.length) console.log('Mancanti:',missing)
if(broken.length) console.log('Relazioni rotte:',broken)
if(noSources.length) console.log('Senza fonti:',noSources)
if(missing.length||broken.length||noSources.length) throw new Error('Audit NT core non superato.')
console.log('\n✓ Audit NT core superato.')
